[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
  let g:gruvbox_italic=1
  let g:gruvbox_contrast_light='medium'
'''

[[plugins]]
repo = 'fuenor/im_control.vim'
hook_add = '''
  let g:IM_CtrlMode=6
  let g:IMState=0
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = ['gruvbox']
hook_add = '''
'''

[[plugins]]
repo = 'osyo-manga/vim-brightest'
hook_add = '''
  let g:brightest#highlight={
        \   "group" : "BrightestUnderline",
        \ }
  let g:brightest#pattern='\w\{2,}'
  let g:brightest#enable_on_CursorHold=0
'''

[[plugins]]
repo = 'spolu/dwm.vim'
hook_add = '''
  tnoremap <C-j> <C-\><C-n><C-j>
  tnoremap <C-k> <C-\><C-n><C-k>
  tnoremap <C-@> <C-\><C-n><C-@>
  nnoremap <C-p> :call DWM_Focus()<CR>
  " set master pane width
  let g:dwm_master_pane_width=90
'''

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'gnperdue/vim-asciidoc'

[[plugins]]
repo = 'plasticboy/vim-markdown'
hook_add = '''
  let g:vim_markdown_no_default_key_mappings=1
  let g:vim_markdown_folding_disabled=1
'''

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
  let g:EasyMotion_do_mapping = 0 " Disable default mappings
  nmap f <Plug>(easymotion-overwin-f2)
  let g:EasyMotion_smartcase = 1
'''
